TabBar/Tabs using a type instead of usize for active_tab
iced-rs/iced_aw pull request #128
Opened 2023-06-02 15:45 UTC by andretietz

Hey there!

I created the feature request #124 and since I didn't want to wait for it, I just implemented it.
It's not done yet but, I wanted to hear your impression, so that I won't run into a complete wrong direction.

TODO:

* ATM There's no check if there are 2 indices duplicated on the TabBar/Tabs. I need to check this as non-verbose as possible. I want to avoid Result-Type for the `new`-function, but I am not sure if this is possible with this implementation. Any ideas?

2023-06-02 15:47 UTC, andretietz commented on src/native/tab_bar.rs
> +/// # pub type TabBar<Message> = tab_bar::TabBar<Message, u32, Null>;
needs change!

2023-06-02 15:47 UTC, andretietz commented on src/native/tab_bar.rs
> +    /// The index and identifier of the currently active tab.
needs change

2023-06-02 15:48 UTC, andretietz commented on src/native/tab_bar.rs
> +    pub fn width_tab_labels<F>(active_tab: TabId, tab_labels: Vec<(TabId, TabLabel)>, on_select: F) -> Self
Not sure about the vector tuple here, wdyt?

2023-06-02 17:10 UTC, genusistimelord requested changes
I request you get this update with the current main. Also everything else looks good. would be nice to see an tab ID enum used in the example though.

2023-06-02 17:10 UTC, genusistimelord commented on src/graphics/tabs.rs
you may want to take a look at some of the new changes in iced_aw as I started to align it with how iced is and got rid of the graphics section other than for fonts. So you will want to merge those changes over.

2023-06-02 18:09 UTC, andretietz commented
> 

The example you're searching is [here](https://github.com/iced-rs/iced_aw/pull/128/files#diff-7306b5cc679881d4f177368c6abf45a59d7680af74363b275a046921f72372b4) or do you mean another place?

In the TabBar example I am using usize as custom type.

2023-06-02 18:18 UTC, andretietz commented
Sorry, still WIP

2023-06-05 08:43 UTC, andretietz commented
Ok, I believe I am done with the Feature request #124. Please review and feel free to squash-merge, when done.

2023-06-05 12:33 UTC, genusistimelord approved these changes

2023-06-05 12:44 UTC, merged

2023-06-05 12:44 UTC, genusistimelord commented
thank you for your hard work.